### ISSUE TITLE
Add EPQ-N and BFI-N to supplement

### ISSUE THREAD

**Issue by dr-consulting** [dr-consulting/shackman-umd-pax-ema-pub#26]
# Context
We are using a slightly different measure of dispositional negativity than more commonly used scales like the BFI and EPQ. We did collect these data in the PAX sample (used in Study 2). 

# Tasks
1. Create neuroticism summary scores using standard methodology for the BFI and EPQ
1. Compute alpha & omega for the scales
1. Create a table that includes these summary stats and include in the supplement
1. Compute and report Pearson's *r* (or R-squared) - probably most easily summarized with a two-panel figure in the supplement

# Conditions of Satisfaction
- [ ] There is a one-sentence summary in the manuscript that points the reader to the supplement
- [ ] The summary statistics for the BFI and EPQ are included in an appropriately labeled table in the supplement
- [ ] The association between our DN score and both the BFI-N and EPQ-N is reasonably summarized either graphically, statistically or a combination thereof.

**Comment by dr-consulting** [comment]
Work on this issue to begin when @ajshackman has completed his review of the current manuscript. Noting as a separate revision task for tracking purposes.
